//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.06 at 04:39:18 PM BRT 
//


package br.com.sysmap.crux.core.rebind.screen.config.parser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.sysmap.crux.core.rebind.screen.config.parser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Crux_QNAME = new QName("", "crux");
    private final static QName _Widget_QNAME = new QName("", "widget");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.sysmap.crux.core.rebind.screen.config.parser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CruxT }
     * 
     */
    public CruxT createCruxT() {
        return new CruxT();
    }

    /**
     * Create an instance of {@link WidgetT }
     * 
     */
    public WidgetT createWidgetT() {
        return new WidgetT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CruxT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "crux")
    public JAXBElement<CruxT> createCrux(CruxT value) {
        return new JAXBElement<CruxT>(_Crux_QNAME, CruxT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WidgetT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "widget")
    public JAXBElement<WidgetT> createWidget(WidgetT value) {
        return new JAXBElement<WidgetT>(_Widget_QNAME, WidgetT.class, null, value);
    }

}
