(function(l){function v(){n=!1;var a=p;p=[];a.sort(function(b,a){return b.uid_-a.uid_});var b=!1;a.forEach(function(a){var d=a.takeRecords();A(a);d.length&&(a.callback_(d,a),b=!0)});b&&v()}function A(a){a.nodes_.forEach(function(b){(b=f.get(b))&&b.forEach(function(b){b.observer===a&&b.removeTransientObservers()})})}function q(a,b){for(var c=a;c;c=c.parentNode){var d=f.get(c);if(d)for(var e=0;e<d.length;e++){var g=d[e],h=g.options;(c===a||h.subtree)&&(h=b(h))&&g.enqueue(h)}}}function r(a){this.callback_=
a;this.nodes_=[];this.records_=[];this.uid_=++B}function w(a,b){this.type=a;this.target=b;this.addedNodes=[];this.removedNodes=[];this.oldValue=this.attributeNamespace=this.attributeName=this.nextSibling=this.previousSibling=null}function t(a,b){return m=new w(a,b)}function x(a){if(g)return g;var b=m,c=new w(b.type,b.target);c.addedNodes=b.addedNodes.slice();c.removedNodes=b.removedNodes.slice();c.previousSibling=b.previousSibling;c.nextSibling=b.nextSibling;c.attributeName=b.attributeName;c.attributeNamespace=
b.attributeNamespace;c.oldValue=b.oldValue;g=c;g.oldValue=a;return g}function y(a,b,c){this.observer=a;this.target=b;this.options=c;this.transientObservedNodes=[]}var f=new WeakMap,k;if(/Trident|Edge/.test(navigator.userAgent))k=setTimeout;else if(window.setImmediate)k=window.setImmediate;else{var u=[],z=String(Math.random());window.addEventListener("message",function(a){a.data===z&&(a=u,u=[],a.forEach(function(a){a()}))});k=function(a){u.push(a);window.postMessage(z,"*")}}var n=!1,p=[],B=0;r.prototype=
{observe:function(a,b){var c=a;a=window.ShadowDOMPolyfill&&window.ShadowDOMPolyfill.wrapIfNeeded(c)||c;if(!b.childList&&!b.attributes&&!b.characterData||b.attributeOldValue&&!b.attributes||b.attributeFilter&&b.attributeFilter.length&&!b.attributes||b.characterDataOldValue&&!b.characterData)throw new SyntaxError;(c=f.get(a))||f.set(a,c=[]);for(var d,e=0;e<c.length;e++)if(c[e].observer===this){d=c[e];d.removeListeners();d.options=b;break}d||(d=new y(this,a,b),c.push(d),this.nodes_.push(a));d.addListeners()},
disconnect:function(){this.nodes_.forEach(function(a){a=f.get(a);for(var b=0;b<a.length;b++){var c=a[b];if(c.observer===this){c.removeListeners();a.splice(b,1);break}}},this);this.records_=[]},takeRecords:function(){var a=this.records_;this.records_=[];return a}};var m,g;y.prototype={enqueue:function(a){var b=this.observer.records_,c=b.length;if(0<b.length){var d=b[c-1];d=d===a?d:!g||d!==g&&d!==m?null:g;if(d){b[c-1]=d;return}}else p.push(this.observer),n||(n=!0,k(v));b[c]=a},addListeners:function(){this.addListeners_(this.target)},
addListeners_:function(a){var b=this.options;b.attributes&&a.addEventListener("DOMAttrModified",this,!0);b.characterData&&a.addEventListener("DOMCharacterDataModified",this,!0);b.childList&&a.addEventListener("DOMNodeInserted",this,!0);(b.childList||b.subtree)&&a.addEventListener("DOMNodeRemoved",this,!0)},removeListeners:function(){this.removeListeners_(this.target)},removeListeners_:function(a){var b=this.options;b.attributes&&a.removeEventListener("DOMAttrModified",this,!0);b.characterData&&a.removeEventListener("DOMCharacterDataModified",
this,!0);b.childList&&a.removeEventListener("DOMNodeInserted",this,!0);(b.childList||b.subtree)&&a.removeEventListener("DOMNodeRemoved",this,!0)},addTransientObserver:function(a){if(a!==this.target){this.addListeners_(a);this.transientObservedNodes.push(a);var b=f.get(a);b||f.set(a,b=[]);b.push(this)}},removeTransientObservers:function(){var a=this.transientObservedNodes;this.transientObservedNodes=[];a.forEach(function(a){this.removeListeners_(a);a=f.get(a);for(var c=0;c<a.length;c++)if(a[c]===this){a.splice(c,
1);break}},this)},handleEvent:function(a){a.stopImmediatePropagation();switch(a.type){case "DOMAttrModified":var b=a.attrName,c=a.relatedNode.namespaceURI,d=a.target,e=new t("attributes",d);e.attributeName=b;e.attributeNamespace=c;var f=a.attrChange===MutationEvent.ADDITION?null:a.prevValue;q(d,function(a){if(a.attributes&&(!a.attributeFilter||!a.attributeFilter.length||-1!==a.attributeFilter.indexOf(b)||-1!==a.attributeFilter.indexOf(c)))return a.attributeOldValue?x(f):e});break;case "DOMCharacterDataModified":d=
a.target;e=t("characterData",d);f=a.prevValue;q(d,function(a){if(a.characterData)return a.characterDataOldValue?x(f):e});break;case "DOMNodeRemoved":this.addTransientObserver(a.target);case "DOMNodeInserted":var h=a.target,k;"DOMNodeInserted"===a.type?(d=[h],k=[]):(d=[],k=[h]);var l=h.previousSibling,h=h.nextSibling,e=t("childList",a.target.parentNode);e.addedNodes=d;e.removedNodes=k;e.previousSibling=l;e.nextSibling=h;q(a.relatedNode,function(a){if(a.childList)return e})}m=g=void 0}};l.JsMutationObserver=
r;l.MutationObserver||(l.MutationObserver=r)})(this);