//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.16 at 06:45:42 PM BRST 
//


package br.com.sysmap.crux.core.server.screen.config.parser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for componentT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="componentT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="clientClass" type="{http://www.w3.org/2001/XMLSchema}string" default="br.com.sysmap.crux.core.client.component.Component" />
 *       &lt;attribute name="clientConstructorParams" type="{http://www.w3.org/2001/XMLSchema}string" default=" " />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parserInput" type="{}parserType" default="jericho" />
 *       &lt;attribute name="serverClass" type="{http://www.w3.org/2001/XMLSchema}string" default="br.com.sysmap.crux.core.server.screen.Component" />
 *       &lt;attribute name="serverParserClass" type="{http://www.w3.org/2001/XMLSchema}string" default="br.com.sysmap.crux.core.server.screen.ComponentParserImpl" />
 *       &lt;attribute name="serverRendererClass" type="{http://www.w3.org/2001/XMLSchema}string" default="br.com.sysmap.crux.core.server.screen.ComponentRendererImpl" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "componentT")
public class ComponentT {

    @XmlAttribute
    protected String clientClass;
    @XmlAttribute
    protected String clientConstructorParams;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected ParserType parserInput;
    @XmlAttribute
    protected String serverClass;
    @XmlAttribute
    protected String serverParserClass;
    @XmlAttribute
    protected String serverRendererClass;

    /**
     * Gets the value of the clientClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientClass() {
        if (clientClass == null) {
            return "br.com.sysmap.crux.core.client.component.Component";
        } else {
            return clientClass;
        }
    }

    /**
     * Sets the value of the clientClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientClass(String value) {
        this.clientClass = value;
    }

    /**
     * Gets the value of the clientConstructorParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientConstructorParams() {
        if (clientConstructorParams == null) {
            return " ";
        } else {
            return clientConstructorParams;
        }
    }

    /**
     * Sets the value of the clientConstructorParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientConstructorParams(String value) {
        this.clientConstructorParams = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parserInput property.
     * 
     * @return
     *     possible object is
     *     {@link ParserType }
     *     
     */
    public ParserType getParserInput() {
        if (parserInput == null) {
            return ParserType.JERICHO;
        } else {
            return parserInput;
        }
    }

    /**
     * Sets the value of the parserInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParserType }
     *     
     */
    public void setParserInput(ParserType value) {
        this.parserInput = value;
    }

    /**
     * Gets the value of the serverClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerClass() {
        if (serverClass == null) {
            return "br.com.sysmap.crux.core.server.screen.Component";
        } else {
            return serverClass;
        }
    }

    /**
     * Sets the value of the serverClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerClass(String value) {
        this.serverClass = value;
    }

    /**
     * Gets the value of the serverParserClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerParserClass() {
        if (serverParserClass == null) {
            return "br.com.sysmap.crux.core.server.screen.ComponentParserImpl";
        } else {
            return serverParserClass;
        }
    }

    /**
     * Sets the value of the serverParserClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerParserClass(String value) {
        this.serverParserClass = value;
    }

    /**
     * Gets the value of the serverRendererClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerRendererClass() {
        if (serverRendererClass == null) {
            return "br.com.sysmap.crux.core.server.screen.ComponentRendererImpl";
        } else {
            return serverRendererClass;
        }
    }

    /**
     * Sets the value of the serverRendererClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerRendererClass(String value) {
        this.serverRendererClass = value;
    }

}
